replicaCount: 3

image:
  repository: sifytul/api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

podAntiAffinity:
  enabled: true
  topologyKey: kubernetes.io/hostname
